[project]
name = "fastapi-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.120.2",
    "fastapi>=0.141.1",
    "huggingface-hub>=1.27.0",
    "openai>=2.53.0",
    "pydantic-settings>=2.15.0",
    "sse-starlette>=3.4.8",
    "uvicorn[standard]>=0.52.1",
]
