"""Rotating status lines shown during the /challenge-me SSE stream."""

GENERATING_LINES: list[str] = [
    "Preparing a reason why you're wrong...",
    "Cooking up some brutal honesty...",
    "Loading maximum sass...",
    "Sharpening the knives...",
    "Consulting my inner asshole...",
    "Summoning zero empathy...",
    "Calculating exactly how wrong you are...",
    "Drafting your reality check...",
    "Rehearsing my rebuttal in the mirror...",
    "Warming up the disappointment engine...",
    "Fact-checking your entire personality...",
    "Polishing a comeback with your name on it...",
    "Downloading a spine for this argument...",
    "Stretching before I roast you...",
    "Filing a formal objection to your vibe...",
    "Recalculating the odds you're right (still zero)...",
    "Charging up the side eye...",
    "Popping the cork on some premium spite...",
    "Grabbing my red pen for your life choices...",
    "Consulting the ancient scrolls of \"nope\"...",
    "Auditing your logic for structural damage...",
]

REGENERATING_LINES: list[str] = [
    "Dealing with another nonsense...",
    "That wasn't harsh enough. Trying again...",
    "Back to the drawing board, but meaner...",
    "Nope, too nice. Redoing...",
    "Recalibrating the savagery...",
    "You really wanted worse? Bet...",
    "Turning the mean dial up...",
    "Scrapping that, going feral...",
    "Nope, that draft had feelings. Fixing it...",
    "Ugh, I was almost agreeable. Never again...",
    "Insufficient contempt detected. Adjusting...",
    "That draft got benched for being soft...",
    "Somehow I sounded reasonable. Unacceptable...",
    "Deleting that and my sympathy...",
    "That was a warning shot. Bringing the real one...",
    "Not enough eye-rolling. Redrafting...",
    "Loading a version with actual teeth...",
    "That draft was practically a compliment. Fixing that...",
    "Second verse, meaner than the first...",
    "My inner critic said \"be worse.\" Complying...",
    "Nice almost slipped through. Stopping that...",
]

REVIEWING_LINES: list[str] = [
    "Fact-checking the savagery...",
    "Making sure this really stings...",
    "Running quality control on the roast...",
    "Checking if this crosses a line (it does)...",
    "Peer-reviewing the burn...",
    "Taste-testing for maximum sting...",
    "Confirming this will ruin your day...",
    "Final polish on the roast...",
    "Cross-referencing this burn with the facts (they check out)...",
    "Calibrating the disrespect to the correct dosage...",
    "Double-checking the receipts before serving them...",
    "Grading this on a curve (you still fail)...",
    "Verifying the shade meets our standards...",
    "Stress-testing the comeback for weak spots...",
    "Consulting the panel of judges (they're brutal)...",
    "Proofreading the disappointment...",
    "Vetting the insult for plausible deniability...",
    "Rating the smackdown out of ten...",
    "Inspecting the sass levels with a magnifying glass...",
    "Giving this insult a once-over before it ships...",
    "Benchmarking this roast against your worst qualities...",
]
